theme: jekyll-theme-minimal
title: KlaymeaN
description: Welcome to my website, where I share things that I believe are worth sharing!
url: "klaymean.github.io"


nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"
